services:
  controller:
    build: ./controller
    container_name: controller
    volumes:
      - ./data:/data

  risk-engine:
    build: ./risk_engine
    container_name: risk-engine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ./risk_engine/config:/opt/security/config:ro
    depends_on:
      - controller

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "8000:5000"
    volumes:
      - ./data:/data
    depends_on:
      - risk-engine

  node1:
    build: ./node_agent
    container_name: node1
    depends_on:
      - controller

  node2:
    build: ./node_agent
    container_name: node2
    depends_on:
      - controller

  node3:
    build: ./node_agent
    container_name: node3
    depends_on:
      - controller

  node4:
    build: ./node_agent
    container_name: node4
    depends_on:
      - controller

  wazuh:
    build: ./wazuh
    container_name: wazuh
