#!/usr/bin/env python3
"""
generate_baseline.py — Config File Baseline Hash Generator

Run this script ONCE from a known-good node state to capture
the SHA-256 hashes of monitored configuration files.

Output is written to: risk_engine/config/config_hashes.yaml

Usage:
    python3 generate_baseline.py [--files /etc/hosts,/etc/passwd,/etc/sudoers]
    python3 generate_baseline.py --out ./risk_engine/config/config_hashes.yaml
"""

import argparse
import hashlib
import sys
from pathlib import Path

import yaml

DEFAULT_FILES = ["/etc/hosts", "/etc/passwd", "/etc/sudoers"]
DEFAULT_OUT   = "./risk_engine/config/config_hashes.yaml"


def sha256_file(path: str) -> str | None:
    try:
        h = hashlib.sha256()
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(65536), b""):
                h.update(chunk)
        return h.hexdigest()
    except OSError as e:
        print(f"  [WARN] Cannot read {path}: {e}", file=sys.stderr)
        return None


def main():
    parser = argparse.ArgumentParser(description="Generate config file baseline hashes.")
    parser.add_argument(
        "--files",
        default=",".join(DEFAULT_FILES),
        help="Comma-separated list of files to hash.",
    )
    parser.add_argument(
        "--out",
        default=DEFAULT_OUT,
        help="Output YAML path.",
    )
    args = parser.parse_args()

    files  = [f.strip() for f in args.files.split(",") if f.strip()]
    hashes = {}

    print(f"Computing baseline hashes for {len(files)} file(s)...")
    for fpath in files:
        digest = sha256_file(fpath)
        if digest:
            hashes[fpath] = digest
            print(f"  OK  {fpath}: {digest[:16]}...")
        else:
            print(f"  SKIP {fpath} (unreadable)")

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    header = (
        "# Baseline SHA-256 hashes of monitored configuration files.\n"
        "# Generated by generate_baseline.py — DO NOT edit manually.\n"
        f"# Files: {', '.join(files)}\n"
        "#\n"
        "# Regenerate from a known-good node with:\n"
        "#   python3 generate_baseline.py\n\n"
    )

    with open(out_path, "w") as f:
        f.write(header)
        yaml.dump(hashes, f, default_flow_style=False)

    print(f"\nBaseline written to: {out_path}")
    print(f"Total files hashed: {len(hashes)}")


if __name__ == "__main__":
    main()
